<?php

namespace App\DB\Models;

use Illuminate\Database\Eloquent\Model;

class Tasks extends Model
{
    protected $fillable = ['id'];
    public function user () {
        return $this->hasOne('App\DB\Models\User');
    }

    public function comments(){
        return $this->hasMany(Comments::class, 'task_id', 'id');
    }

    public function project() {
        return $this->belongsTo(Project::class);
    }

    public function delete()
    {
        $this->comments()->delete();
        return parent::delete(); // TODO: Change the autogenerated stub
    }
}
